name: saguapac
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter_icons:
  image_path: 'images/app.png'
  android: true
  ios: true

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animate_do: ^2.0.0
  provider: ^5.0.0
  flutter_launcher_icons: ^0.9.0
  panorama: ^0.4.1
  flutter_native_splash: ^1.1.8+4
  sizer: ^2.0.13
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  http: ^0.13.4
  dart_random_choice: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  fonts:
    - family: MontserratMediumItalic
      fonts:
        - asset: fonts/Montserrat-MediumItalic.ttf

    - family: MontserratExtraBold
      fonts:
        - asset: fonts/Montserrat-ExtraBold.ttf

    - family: MontserratMedium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

    - family: MontserratSemiBold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf

    - family: MontserratRegular
      fonts:
        - asset: fonts/Montserrat-Regular.ttf


  uses-material-design: true
  assets:
    - images/

flutter_native_splash:
  color: "ffffff"
